### ISSUE TITLE
Sliders not visible since 2021-05 update for light-group entities if the light is off

### ISSUE THREAD

**Issue by DanielWinks** [thomasloven/lovelace-slider-entity-row#194]
My Home Assistant version: 2021.05.x

My lovelace configuration method (GUI or yaml): GUI

What I am doing: Adding light group to UI with slider visible

What I expected to happen: Visible slider

What happened instead: No visible slider until light is turned on

**Minimal** steps to reproduce: Create light group, add light group entity to UI

```yaml
# UI
entity: light.family_room_overhead_light
type: 'custom:slider-entity-row'
toggle: true
name: Family Room
```
```yaml
# Light group (this is 4 identical RGBW bulbs, Inovelli Ilumin specifically)
light:
  - platform: group
    name: Family Room Overhead Light
    entities:
      - light.family_room_overhead_rgbw1
      - light.family_room_overhead_rgbw2
      - light.family_room_overhead_rgbw3
      - light.family_room_overhead_rgbw4
```
Error messages from the browser console:
None
---

**By putting an X in the boxes ([X]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).
- [X] Have made sure I am using the latest version of the plugin.
- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.
- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by DanielWinks** [comment]
Note that regular entities work fine. It's just the light group that doesn't show the slider unless the light is turned on. Turning the light on first, so the slider is visible, turns the light on to 100% brightness, which is definitely less than ideal. Having the slider available at all times allows for turning the light directly on to a specific %.

This worked without any other changes, other than updating to 2021.05. It was working as expected on 2021.04. No changes to UI or light group was made between when it was working and when it stopped. Appears to be some interaction difference between 2021.04 and 2021.05 and the slider entity row card.

**Comment by CDRX2** [comment]
+1

**Comment by bcmitri** [comment]
+1

**Comment by Andrewpaps** [comment]
+1

**Comment by richie-svk** [comment]
same here

**Comment by cyber-arche** [comment]
Also experiencing the same issue.

**Comment by HunterH-Sudo** [comment]
I'm having the same issue, however it's with my Tasmota intergrade bulbs. As soon as they shut off the slider just disappeares

**Comment by galak** [comment]
Any updates here?

**Comment by moezkorkmaz** [comment]
+1

**Comment by csicar** [comment]
The problem is caused by the supported attribute detection here: https://github.com/thomasloven/lovelace-slider-entity-row/blob/master/src/controllers/light-controller.ts#L157

At least in my case `c.stateObj.attributes.supported_features == 32`, so masking with `& 1` yields zero.
The individual lights in the group have `supported_faatures == 35`, so masking succeeds. 
(You can check your values under developer-tools > state and look for the `supported_features` of the entitites)

According to https://github.com/home-assistant/frontend/blob/dev/src/data/light.ts#L34 means `SUPPORT_TRANSITION`. So maybe the problem comes from home assistant itself?

**Comment by Andoramb** [comment]
+1

**Comment by moto3001** [comment]
Also having this issue of sliders disappearing since updating to 2021.6.0.  Sliders were showing fine in 2021.5.0.

**Comment by mckochan** [comment]
+1 Slider disappeas for my z-wave dimmer light in 2021.6.0. Worked fine in 2021.4.6

**Comment by guidokieboom** [comment]
I'm also having this issue since updating to 2021.6.0 (worked fine in prior HA versions): no sliders for Tasmota light bulbs when 0% or toggled off ("Lamp TV example); slider remains for Shelly dimmers when 0% or toggled off ("Achterdeur example"). Would like it to get back with all sliders when at 0%.
<img width="374" alt="Screenshot 2021-06-03 at 20 28 29" src="https://user-images.githubusercontent.com/65387179/120694305-538a7780-c4aa-11eb-8e7e-972fe45c9fa0.png">
this becomes:
<img width="364" alt="Screenshot 2021-06-03 at 20 28 13" src="https://user-images.githubusercontent.com/65387179/120694317-571dfe80-c4aa-11eb-8558-a1fb2a3ee60c.png">

**Comment by paulearley** [comment]
+1. Looking into the code now.

**Comment by thomasloven** [comment]
Try 17.1.0

**Comment by ee02217** [comment]
Updated and still the same behaviour.

**Comment by pippyn** [comment]
The latest version works. You'll have to flush your browser cache/hard refresh.

**Comment by richie-svk** [comment]
Still not working. Updated to 17.1.0; restarted; reset the frontend cache, rebooted again. Reinstalled the repository… still the same. No slider. I am on HA 2021.6.0.

**Comment by DasLetzteEinhorn** [comment]
> The latest version works. You'll have to flush your browser cache/hard refresh.

I can confirm, it works now again. 


> Still not working. Updated to 17.1.0; restarted; reset the frontend cache, rebooted again. Reinstalled the repository… still the same. No slider. I am on HA 2021.6.0.
I had to empty the cache by opening the dev options in chrome (F12) and right click on the refresh button -> empty cache

**Comment by thomasloven** [comment]
If it doesn't work, please post exactly what your browser console says about "SLIDER-ENTITY-ROW" and the full list of attributes for the lights not working as expected.

**Comment by ChrisBaker97** [comment]
For anyone else using the iOS app, after updating, it will say you need to flush the cache, and a button in that dialog is labeled "RELOAD" but that doesn't actually seem to flush the cache. It didn't start working for me until I went into App Configuration | Debugging | Reset frontend cache.

**Comment by ee02217** [comment]
It’s working now. Thank you very much!!

**Comment by Andoramb** [comment]
Yes, all good. Tack!

**Comment by Andrewpaps** [comment]
Can also report fixed as of 17.1.0. Thanks for the work @thomasloven. And fixed on iOS after resetting frontend cache, thanks @ChrisBaker97.

**Comment by richie-svk** [comment]
Still doesnt work on ios. Tried via app, safari, chrome.
Ha restart, clear chache, uninstall and install.. nothing.

Code:

- type: custom:slider-entity-row
    entity: light.shellydimmer2_xxxxxxxx_light_0
    icon: mdi:lightbulb
    name: Obyvacka
    hide_state: true
    step: 1
    max: 60

![F34FD5F4-D55E-4946-95EE-85C95856BE4E](https://user-images.githubusercontent.com/76554425/120806168-cfd29880-c546-11eb-9fd2-bebaedb92116.png)
![BB170372-2002-4CCF-9383-37C2E7A7990F](https://user-images.githubusercontent.com/76554425/120806237-e547c280-c546-11eb-83dd-67f8df3b3905.jpeg)

**Comment by thomasloven** [comment]
> If it doesn't work, please post exactly what your browser console says about "SLIDER-ENTITY-ROW" and the full list of attributes for the lights not working as expected.

**Comment by bcmitri** [comment]
The latest version seems to fix the problem for me on _most_ platforms.  The only one that's still experiencing an issue is Opera on an old Android tablet (I use this since it has a full-screen mode).  Chrome on the same tablet works fine, so it seems to just be Opera.  Unfortunately, I don't know that Opera has any sort of browser console for me to provide additional details.

**Comment by DanielWinks** [comment]
This issues has been resolved with update 17.1.0. A few devices I tried it on required forcibly clearing caches to begin working, but the fixes in 17.1.0 do seem to resolve this. I suspect anyone still having issues after 17.1.0 are being caused by their browser using cached data.

**Comment by bcmitri** [comment]
I can agree with that statement.  I thought I had cleared my cache, but it turns out I hadn't.  After correctly clearing my cache, the issue is corrected on all of my platforms.

**Comment by richie-svk** [comment]
I am so happy it works for you guys and I am so frustrated it doesn't work for me :(
I tried on multiple browsers - some I never used before (so nothing to clean cache).

The Chrome console says: SLIDER-ENTITY-ROW 1.0.0 IS INSTALLED 

should that be 17.1.0 instead? is that somehow a problem?

Thanks.
Richard.

**Comment by zigomatichub** [comment]
Hello, 
Version info:
core-2021.6.2
supervisor-2021.05.4
SLIDER-ENTITY-ROW 17.0.1 (in console)

I observe slider is not coming in group if it's value is at 0.
If I push one of the light that are in the group, the slider of the group is updated.

**Comment by thomasloven** [comment]
If it doesn't say `SLIDER-ENTITY-ROW 17.1.0 IS INSTALLED` you probably haven't updated correctly or have more than one instance installed.

- Re-read the installation/upgrade guide linked from the readme
- Remove slider-entity-row completely
- Reinstall (preferably through HACS)
- Clear your cache and reload (also in the guide)

**Comment by richie-svk** [comment]
Good point. Even if I remove it from HACS, it still works (with the bug). So that confirms what you say - there is another instance messing with it. How do I remove that? I restarted HA after removal, also looked in the files, but couldn’t find anything related.

**Comment by zigomatichub** [comment]
@thomasloven. Correct, I updated manualy in HACS by clicking on reinstall because HACS don't say anything about a new version.
Now the issue is solved :)

**Comment by RedWheiler80** [comment]
> Good point. Even if I remove it from HACS, it still works (with the bug). So that confirms what you say - there is another instance messing with it. How do I remove that? I restarted HA after removal, also looked in the files, but couldn’t find anything related.

Probably you need to go to the map 'www' on your system and there will be an old map with the slider component inside. I had the same 'problem'.

So: delete it in HA, remove it from your raw-editor (if it's still in there), remove it from the 'local' map, reboot the system, make sure cache is clear (so at F12 you don't see any mention about slider entity anymore, and reinstall with HACS.

**Comment by richie-svk** [comment]
> > Good point. Even if I remove it from HACS, it still works (with the bug). So that confirms what you say - there is another instance messing with it. How do I remove that? I restarted HA after removal, also looked in the files, but couldn’t find anything related.
> 
> Probably you need to go to the map 'www' on your system and there will be an old map with the slider component inside. I had the same 'problem'.
> 
> So: delete it in HA, remove it from your raw-editor (if it's still in there), remove it from the 'local' map, reboot the system, make sure cache is clear (so at F12 you don't see any mention about slider entity anymore), and reinstall with HACS.

That helped! Thank you very much. I wouldn’t find it by myself! Thank you. And thank you!
I am very happy about it working again!
Also thanks for the fix of the slider…

**Comment by Lordnnud** [comment]
I've completed all the steps above. The slider works but fails to update the % on the right hand side :-
![image](https://user-images.githubusercontent.com/19661440/126897433-f9a960a3-6db6-4deb-a413-e0b401c5c82f.png)

Any ideas please?
